name: DevOps Coding Challenge

trigger:
- main

pool:
  name: Default
  vmImage: 'ubuntu-latest'

# parameters:
  # tfversion: 3.29.1
  # - name: overrideAction
  #   type: string
  #   default: plan
  #   values:
  #     - plan
  #     - apply

steps:

- task: TerraformInstaller@0
  displayName: 'Install Terraform 3.29.1'
  inputs:
    terraformVersion: '3.29.1'

- script: |
    echo hello
    terraform --version
  displayName: 'Run a script'

  # - task: TerraformCLI@0
  #   displayName: Terraform init -backend=false
  #   inputs:
  #     command: init
  #     terraformVersion: ${{ parameters.tfversion }}

  # - task: TerraformCLI@0
  #   displayName: Terraform plan
  #   inputs:
  #     command: plan
  #     terraformVersion: ${{ parameters.tfversion }}

  # - task: TerraformCLI@0
  #   displayName: Terraform apply
  #   condition: and(succeeded(), eq(variables['Action'], 'Apply'))
  #   inputs:
  #     command: apply
  #     terraformVersion: ${{ parameters.tfversion }}