name: DevOps Coding Challenge

trigger:
- main

pool:
  name: Default
  vmImage: 'ubuntu-latest'

parameters:
  - name: tfversion
    default: 1.3.3
    type: string
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply

steps:

- task: TerraformInstaller@0
  displayName: 'install terraform ${{ parameters.tfversion }}'
  inputs:
    terraformVersion: ${{ parameters.tfversion }}

- task: TerraformCLI@0
  displayName: 'check terraform version'
  inputs:
    command: version

  - task: TerraformCLI@0
    displayName: Terraform init
    inputs:
      command: init
      terraformVersion: ${{ parameters.tfversion }}

  - task: TerraformCLI@0
    displayName: Terraform plan
    inputs:
      command: plan
      terraformVersion: ${{ parameters.tfversion }}

  # - task: TerraformCLI@0
  #   displayName: Terraform apply
  #   condition: and(succeeded(), eq(variables['Action'], 'Apply'))
  #   inputs:
  #     command: apply
  #     terraformVersion: ${{ parameters.tfversion }}